#!/bin/bash

set -ouex pipefail

# Remove unneeded repositories and update
rm -f /etc/apt/apt.conf.d/docker-gzip-indexes /etc/apt/apt.conf.d/docker-no-languages
rm -f /var/log/apt/eipp.log.xz
apt update -y

# Required packages
apt install -y \
  btrfs-progs \
  ca-certificates \
  curl \
  dracut \
  dosfstools \
  e2fsprogs \
  fdisk \
  firmware-linux-free \
  iproute2 \
  iputils-ping \
  linux-image-generic \
  network-manager \
  skopeo \
  sudo \
  systemd \
  systemd-boot-* \
  xfsprogs \
  zstd 

# Use proper home directory for new users
sed -i 's|.*HOME=/home|HOME=/var/home|' "/etc/default/useradd"

# Enable boot.mount explicitly
systemctl enable home.mount
systemctl enable root.mount
systemctl enable srv.mount
systemctl enable mnt.mount

# Fix permissions on sudoers.d
chmod 440 /etc/sudoers.d/001-bootc

# Add build information to os-release
echo "BUILD_ID=\"$BUILD_ID\"" >> /usr/lib/os-release